
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENQUE = 17;
  public static final int RIMPRIMIR = 25;
  public static final int Y = 15;
  public static final int RSTRING = 32;
  public static final int POR = 12;
  public static final int CONCAT = 14;
  public static final int CHARAC = 23;
  public static final int ENTERO = 19;
  public static final int O = 16;
  public static final int LLAVIZQ = 5;
  public static final int RELSE = 29;
  public static final int IDENTIFICADOR = 37;
  public static final int RMIENTRAS = 27;
  public static final int IGUAL = 35;
  public static final int CORDER = 8;
  public static final int DIVIDIDO = 13;
  public static final int UMENOS = 24;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int DECIMAL = 20;
  public static final int error = 1;
  public static final int COMA = 7;
  public static final int CADENA = 21;
  public static final int DIF = 36;
  public static final int MENOS = 11;
  public static final int MAYQUE = 18;
  public static final int RCHAR = 34;
  public static final int LLAVDER = 6;
  public static final int RIMPRIMIRLN = 26;
  public static final int PTCOMA = 2;
  public static final int BOOLEANO = 22;
  public static final int RINT = 31;
  public static final int PARDER = 4;
  public static final int RFOR = 30;
  public static final int CORIZQ = 9;
  public static final int RBOOL = 33;
  public static final int RIF = 28;
  public static final int MAS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "LLAVIZQ",
  "LLAVDER",
  "COMA",
  "CORDER",
  "CORIZQ",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "CONCAT",
  "Y",
  "O",
  "MENQUE",
  "MAYQUE",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "BOOLEANO",
  "CHARAC",
  "UMENOS",
  "RIMPRIMIR",
  "RIMPRIMIRLN",
  "RMIENTRAS",
  "RIF",
  "RELSE",
  "RFOR",
  "RINT",
  "RSTRING",
  "RBOOL",
  "RCHAR",
  "IGUAL",
  "DIF",
  "IDENTIFICADOR"
  };
}

